# from https://github.com/concourse/concourse-docker/blob/master/docker-compose.yml

version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse_user
      POSTGRES_PASSWORD: concourse_pass

  web:
    image: concourse/concourse:5.6.0
    command: web
    links: [db]
    depends_on: [db]
    ports: ["8080:8080"]
    volumes:
      - "./keys:/concourse-keys"
      - "./vault/vault-certs:/vault-certs"
    environment:
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_SESSION_SIGNING_KEY: /concourse-keys/web/session_signing_key
      CONCOURSE_TSA_HOST_KEY: /concourse-keys/web/tsa_host_key
      CONCOURSE_TSA_AUTHORIZED_KEYS: /concourse-keys/worker/authorized_worker_keys
      CONCOURSE_VAULT_URL: https://vault:8200
      CONCOURSE_VAULT_AUTH_BACKEND: cert
      CONCOURSE_VAULT_CA_CERT: /vault-certs/vault-ca.crt
      CONCOURSE_VAULT_CLIENT_CERT: /vault-certs/concourse.crt
      CONCOURSE_VAULT_CLIENT_KEY: /vault-certs/concourse.key

  worker:
    image: concourse/concourse
    command: worker
    privileged: true
    depends_on: [web]
    volumes: ["./keys:/concourse-keys"]
    links: [web]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: web:2222
      CONCOURSE_TSA_PUBLIC_KEY: /concourse-keys/web/tsa_host_key.pub
      CONCOURSE_TSA_WORKER_PRIVATE_KEY: /concourse-keys/worker/worker_key

  # see https://concourse-ci.org/vault-credential-manager.html
  vault:
    image: vault
    cap_add: [IPC_LOCK]
    ports: ["8200:8200"]
    volumes:
      - ./vault/vault-certs:/vault/certs
      - ./vault/vault-config:/vault/config
    command: server